#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
setxkbmap de &
nitrogen --restore &
picom &

bspc monitor DP-0 -d firefox1 term misc 
bspc monitor HDMI-0 -d discord firefox2 spotify 

bspc config border_width         0

bspc config window_gap           0

bspc config focused_border_color  \#F0C674 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^4'
bspc rule -a Code desktop='^2'
bspc rule -a okular desktop='^3'
bspc rule -a Screenkey manage=off
bspc rule -a spotify desktop='^4'
